### ISSUE TITLE
Avoid NAG mutations

### ISSUE THREAD

**Issue by BrentLagesse** [BrentLagesse/GuideDonorScheduler#27]
NAG mutations may cause problems.   If the mutation will produce a NAG, then we wlll initially consider it a failure and continue further upstream into the seed to see if we can find another silent mutation.  If all that fails, we will then do the NAG mutation after the recursive call returns.   We will then note (modify MutationTracker) that it was a NAG mutation so that way it can be filtered out later if we learn that NAG mutations just aren't worth doing.

**Comment by Hsaharan16** [comment]
This is fixed, showed output to Talia and she approved it. The code now avoids NAG/NGA/NGG mutations on top strand and CCN/CTN/TCN for reverse strand. If a mutation will result in any of these acids the code keeps going upstream or downstream.
